---
- hosts: all
  name: Install necessary packages.
  become: yes
  tasks:
  - name: Install apache.
    apt: name=apache2 state=present
    notify:
      - restart apache2

  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted